# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename) {
    .Call('_SeuratBasics_RunModularityClusteringCpp', PACKAGE = 'SeuratBasics', SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename)
}

RunUMISampling <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_SeuratBasics_RunUMISampling', PACKAGE = 'SeuratBasics', data, sample_val, upsample, display_progress)
}

RunUMISamplingPerCell <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_SeuratBasics_RunUMISamplingPerCell', PACKAGE = 'SeuratBasics', data, sample_val, upsample, display_progress)
}

RowMergeMatrices <- function(mat1, mat2, mat1_rownames, mat2_rownames, all_rownames) {
    .Call('_SeuratBasics_RowMergeMatrices', PACKAGE = 'SeuratBasics', mat1, mat2, mat1_rownames, mat2_rownames, all_rownames)
}

LogNorm <- function(data, scale_factor, display_progress = TRUE) {
    .Call('_SeuratBasics_LogNorm', PACKAGE = 'SeuratBasics', data, scale_factor, display_progress)
}

FastRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_SeuratBasics_FastRowScale', PACKAGE = 'SeuratBasics', mat, scale, center, scale_max, display_progress)
}

Standardize <- function(mat, display_progress = TRUE) {
    .Call('_SeuratBasics_Standardize', PACKAGE = 'SeuratBasics', mat, display_progress)
}

FastSparseRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_SeuratBasics_FastSparseRowScale', PACKAGE = 'SeuratBasics', mat, scale, center, scale_max, display_progress)
}

FastSparseRowScaleWithKnownStats <- function(mat, mu, sigma, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_SeuratBasics_FastSparseRowScaleWithKnownStats', PACKAGE = 'SeuratBasics', mat, mu, sigma, scale, center, scale_max, display_progress)
}

FastCov <- function(mat, center = TRUE) {
    .Call('_SeuratBasics_FastCov', PACKAGE = 'SeuratBasics', mat, center)
}

FastCovMats <- function(mat1, mat2, center = TRUE) {
    .Call('_SeuratBasics_FastCovMats', PACKAGE = 'SeuratBasics', mat1, mat2, center)
}

FastRBind <- function(mat1, mat2) {
    .Call('_SeuratBasics_FastRBind', PACKAGE = 'SeuratBasics', mat1, mat2)
}

FastExpMean <- function(mat, display_progress) {
    .Call('_SeuratBasics_FastExpMean', PACKAGE = 'SeuratBasics', mat, display_progress)
}

SparseRowVar2 <- function(mat, mu, display_progress) {
    .Call('_SeuratBasics_SparseRowVar2', PACKAGE = 'SeuratBasics', mat, mu, display_progress)
}

SparseRowVarStd <- function(mat, mu, sd, vmax, display_progress) {
    .Call('_SeuratBasics_SparseRowVarStd', PACKAGE = 'SeuratBasics', mat, mu, sd, vmax, display_progress)
}

FastLogVMR <- function(mat, display_progress) {
    .Call('_SeuratBasics_FastLogVMR', PACKAGE = 'SeuratBasics', mat, display_progress)
}

RowVar <- function(x) {
    .Call('_SeuratBasics_RowVar', PACKAGE = 'SeuratBasics', x)
}

SparseRowVar <- function(mat, display_progress) {
    .Call('_SeuratBasics_SparseRowVar', PACKAGE = 'SeuratBasics', mat, display_progress)
}

ReplaceColsC <- function(mat, col_idx, replacement) {
    .Call('_SeuratBasics_ReplaceColsC', PACKAGE = 'SeuratBasics', mat, col_idx, replacement)
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call('_SeuratBasics_ComputeSNN', PACKAGE = 'SeuratBasics', nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call('_SeuratBasics_WriteEdgeFile', PACKAGE = 'SeuratBasics', snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call('_SeuratBasics_DirectSNNToFile', PACKAGE = 'SeuratBasics', nn_ranked, prune, display_progress, filename)
}

